# Support WP Update Your Footer by using the funding links below
# Developed and Maintained by Waren Gonzaga

issuehunt: WarenGonzaga/wp-update-your-footer
custom: ['https://wrngnz.ga/bmc','https://wrngnz.ga/paypal']

# Your donation means a lot to me to continue the development of open source project like this.
